# Generated by Django 3.0.7 on 2021-04-06 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filemanager.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryOutput',
            fields=[
                ('process_id', models.CharField(max_length=22, validators=[django.core.validators.MinLengthValidator(22)])),
                ('file_id', models.CharField(max_length=22, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(22)])),
                ('file', models.FileField(storage=filemanager.models.FileManagerProcessesSystemStorage(), upload_to=filemanager.models.get_file_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('F', 'File data'), ('U', 'Remote file URL')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
