# Generated by Django 3.0.7 on 2021-04-09 14:52

import django.core.validators
from django.db import migrations, models
import filemanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_temporaryoutput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryoutput',
            name='file_id',
        ),
        migrations.AlterField(
            model_name='temporaryoutput',
            name='file',
            field=models.FileField(blank=True, storage=filemanager.models.FileManagerProcessesSystemStorage(), upload_to=filemanager.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='temporaryoutput',
            name='process_id',
            field=models.CharField(max_length=22, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(22)]),
        ),
    ]
