# Generated by Django 3.0.7 on 2021-04-09 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_auto_20210409_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryoutput',
            name='file_id',
            field=models.CharField(default='MNMNMNMNMNMNMNMNMNMN', max_length=22, validators=[django.core.validators.MinLengthValidator(22)]),
        ),
    ]
