# Generated by Django 3.0.7 on 2021-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0004_temporaryoutput_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryoutput',
            name='process_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
