# Generated by Django 3.0.7 on 2020-09-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nchan', models.IntegerField()),
                ('experimenter', models.CharField(max_length=50)),
                ('proj_name', models.CharField(max_length=50)),
                ('proj_id', models.CharField(max_length=50)),
                ('meas_date', models.DateTimeField()),
                ('ch_names', models.CharField(max_length=100)),
                ('custom_ref_applied', models.BooleanField()),
            ],
        ),
    ]
